#$ -S /bin/bash
#$ -N make_mod
#$ -V
#$ -cwd
#$ -o /share/ClusterShare/software/contrib/singularity/logs
#$ -e /share/ClusterShare/software/contrib/singularity/logs 
#$ -l mem_requested=16G 
#$ -m bae 
#$ -M $USER@garvan.org.au

set -euxo 

echo -e "Image cache: \t" $image_cache
echo -e "Tool: \t" $tool
echo -e "Repo: \t" $repo
echo -e "Image: \t" $image
echo -e "Tag: \t" $tag

cd $image_cache
singularity pull docker://${repo}/${image}:${tag}
